[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-zip --no-interaction --prefer-dist'
]

[phases.build]
cmds = [
    'cp .env.example .env',
    'php artisan config:clear',
    'php artisan cache:clear',
    'chmod -R 775 storage bootstrap/cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

[variables]
PORT = '8080'
